language = "en"
[db]
[db.default]
host = "localhost"
username = "root"
password = "morose999#"
dbname = "mang"
[db.stats]
host = "localhost"
username = "root"
password = "morose999#"
dbname = "mang_stats"
